#!/bin/bash
set -e

setup_dir=/var/lib/setup_tool

tool_cmd=${1}
tool_name=$(basename ${2} | sed 's|.setup||' )
tool_path=${setup_dir}/${tool_name}
tool_file=${tool_path}/${tool_name}

main() {
	case ${1} in
		install)
			setup_tool ${2}
			source ${tool_file}
			install_tool
			create_version_file
			;;
		update)
			source ${tool_file}
			if update_tool; then
				create_version_file
			fi
			;;
		restore)
			source ${tool_file}
			restore_tool
			create_version_file
			;;
		debug)
			source ${2}
			echo "download url: $(get_download_url)"
			echo "tool version: $(get_version)"
			;;
		*)
			exit 1
			;;
	esac
}

setup_tool() {
	mkdir -p ${tool_path}
	cp ${1} ${tool_file}
}

create_version_file() {
	echo $(get_version) > "${tool_path}/${tool_name}.version"
}

isupdate() {
	local file_version=$(cat ${tool_path}/${tool_name}.version)
	local online_version=$(get_version)
	if [ ${file_version} != ${online_version} ]; then
		true
	else
		false
	fi
}

# send_mail(To, From, Subject, Body)
send_mail() {
local body=$(sed 's/^\t\+//' <<< "${4}")
cat <<EOF | msmtp -a default ${1}
To: ${1}
From: ${2}
Subject: ${3}
${body}
EOF
}

main "$@"
exit 0
